import uuid
from datetime import datetime, date

from sqlalchemy import Boolean, Date, DateTime, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class AdminUser(Base):
    """
    Admin portal users.
    Roles:
      super_admin        — full access, can manage other admins
      admin              — create activities/circulars, view all data
      district_coordinator — view/act on assigned districts only
    """
    __tablename__ = "admin_user"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String(200), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    # super_admin | admin | district_coordinator
    role: Mapped[str] = mapped_column(String(30), nullable=False, default="admin")
    # For district_coordinator: list of district names they can access
    assigned_districts: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return f"<AdminUser {self.email} ({self.role})>"


class Circular(Base):
    """
    Department circulars simplified for librarians.
    Admin pastes original text → AI simplifies → admin reviews → sends.
    """
    __tablename__ = "circular"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    circular_number: Mapped[str] = mapped_column(String(50), nullable=False)
    issue_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    original_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    simplified_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    # draft | published
    status: Mapped[str] = mapped_column(String(20), default="draft", nullable=False)
    # Admin who created it
    created_by_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    sent_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class CircularActionItem(Base):
    """
    Action items extracted (by AI or manually) from a circular.
    Each item can be linked to an ActivityTemplate.
    """
    __tablename__ = "circular_action_item"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    circular_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    activity_template_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    title_kn: Mapped[str] = mapped_column(String(300), nullable=False)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # mandatory | optional
    mandatory: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)


class WeeklyNudge(Base):
    """
    Weekly motivational/activity nudge sent to all librarians.
    Two per week: Monday (activity suggestion) + Thursday (motivational/reminder).
    AI-generated drafts require admin approval before sending.
    """
    __tablename__ = "weekly_nudge"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Monday of the target week
    week_start_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    # monday_activity | thursday_motivational
    nudge_type: Mapped[str] = mapped_column(String(30), nullable=False)
    content_kn: Mapped[str] = mapped_column(Text, nullable=False)
    content_en: Mapped[str | None] = mapped_column(Text, nullable=True)
    # draft | approved | sent
    status: Mapped[str] = mapped_column(String(20), default="draft", nullable=False)
    # ai | manual
    generated_by: Mapped[str] = mapped_column(String(10), default="manual", nullable=False)
    # Null = auto-generated by scheduler job
    created_by_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    sent_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class SpecialDay(Base):
    """
    Special calendar days (national holidays, occasions) used to
    suggest theme-appropriate library activities.
    is_system=True entries are pre-seeded and cannot be deleted.
    year=None means the occasion recurs every year on that month/day.
    """
    __tablename__ = "special_day"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    month: Mapped[int] = mapped_column(Integer, nullable=False)
    day: Mapped[int] = mapped_column(Integer, nullable=False)
    # None = recurring annually; int = one-time on a specific year
    year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    occasion_kn: Mapped[str] = mapped_column(String(200), nullable=False)
    occasion_en: Mapped[str] = mapped_column(String(200), nullable=False)
    is_system: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_by_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
